app/src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $libelle;

    #[ORM\Column(type: 'integer')]
    #[Assert\PositiveOrZero]
    private $price;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $img;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $img_alt;

    #[ORM\Column(type: 'integer', nullable: true)]
    #[Assert\PositiveOrZero]
    private $promo;

    #[ORM\Column(type: 'date', nullable: true)]
    private $when_deleted;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'articles')]
    private $category;

    #[ORM\ManyToMany(targetEntity: CustomerOrder::class, mappedBy: 'article')]
    private $customerOrders;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: ArticleVariation::class)]
    private $variation;

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->customerOrders = new ArrayCollection();
        $this->variation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getImgAlt(): ?string
    {
        return $this->img_alt;
    }

    public function setImgAlt(?string $img_alt): self
    {
        $this->img_alt = $img_alt;

        return $this;
    }

    public function getPromo(): ?int
    {
        return $this->promo;
    }

    public function setPromo(?int $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    public function getWhenDeleted(): ?\DateTimeInterface
    {
        return $this->when_deleted;
    }

    public function setWhenDeleted(?\DateTimeInterface $when_deleted): self
    {
        $this->when_deleted = $when_deleted;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, CustomerOrder>
     */
    public function getCustomerOrders(): Collection
    {
        return $this->customerOrders;
    }

    public function addCustomerOrder(CustomerOrder $customerOrder): self
    {
        if (!$this->customerOrders->contains($customerOrder)) {
            $this->customerOrders[] = $customerOrder;
            $customerOrder->addArticle($this);
        }

        return $this;
    }

    public function removeCustomerOrder(CustomerOrder $customerOrder): self
    {
        if ($this->customerOrders->removeElement($customerOrder)) {
            $customerOrder->removeArticle($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, ArticleVariation>
     */
    public function getVariation(): Collection
    {
        return $this->variation;
    }

    public function addVariation(ArticleVariation $variation): self
    {
        if (!$this->variation->contains($variation)) {
            $this->variation[] = $variation;
            $variation->setArticle($this);
        }

        return $this;
    }

    public function removeVariation(ArticleVariation $variation): self
    {
        if ($this->variation->removeElement($variation)) {
            // set the owning side to null (unless already changed)
            if ($variation->getArticle() === $this) {
                $variation->setArticle(null);
            }
        }

        return $this;
    }
}

app/src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Categorie;
use App\Entity\Category;
use Doctrine\DBAL\Types\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle', TextType::class, [
                'label' => "Titre de l'article :",
            ])
            ->add('price', IntegerType::class, [
                'label' => "Prix :",
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description :',
            ])
            ->add('img', FileType::class, [
                'label' => 'Image principal :',
                'required' => false,
            ])
            ->add('img_alt', FileType::class, [
                'label' => 'Image annexe :',
                'required' => false
            ])
            ->add('promo', IntegerType::class, [
                'label' => "Promo :",
                'required' => false,
            ])
            ->add('category', EntityType::class,[
                'class' => Category::class,
                'choice_label' => "libelle",
                'label' => "Catégories :",
                'multiple' => true,
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

app/src/Controller/admin/ArticlesController.php
<?php

namespace App\Controller\admin;

use App\Entity\Article;
use App\Entity\VariationArticle;
use App\Form\ArticleType;
use App\Form\UpdateArticleType;
use App\Repository\ArticleRepository;
use App\Repository\ArticleVariationRepository;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\VariationArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/admin2/articles")]
class ArticlesController extends AbstractController
{
    #[Route('/', name: 'admin_articles')]
    public function list(ArticleRepository $articleRepository, ArticleVariationRepository $variationArticleRepository)
    {
        // !!! On récupère les variations d'articles
        $v_articles = $variationArticleRepository->findAll();

        $articles = $articleRepository->findAll();

        return $this->render('Components/admin/articles/articles.html.twig',[ 
            'v_articles' => $v_articles,
            'articles' => $articles,
        ]);
    }

    #[Route('/new', name: 'admin_article_new')]
    public function new(Request $request)
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            //On va créer x variation d'article défini dans l'entité
        }

        return $this->render('Components/admin/articles/new_update_article.html.twig', [
            'article' => $article,
            'form' => $form->createView()
        ]);
    }

    #[Route('/update/{id}', name: 'admin_update_article')]
    public function update($id, ArticleRepository $articleRepository, Request $request)
    {
        $article = $articleRepository->find($id);

        $form = $this->createForm(UpdateArticleType::class, $article);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            
        }

        return $this->render('Components/admin/articles/new_update_article.html.twig', [
            'article' => $article,
            'form' => $form->createView()
        ]);
    }

    #[Route('/stock/{id}', name: 'admin_stock_variation_article')]
    public function stock(ArticleVariationRepository $variationArticle)
    {
        return $this->render('Components/admin/articles/stock_article.html.twig', [
            'variationArticle' => $variationArticle
        ]);
    }

    #[Route('/delete/{id}', name: 'admin_delete_article')]
    public function delete(Article $article)
    {
        
    }
}

app/src/Controller/customer/ArticleController.php
<?php

namespace App\Controller\customer;

use App\Entity\Article;
use App\Entity\ArticleVariation;
use App\Repository\ArticleRepository;
use App\Repository\ArticleVariationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/{id}', name: 'article_id')]
    public function article($id, ArticleRepository $articleRepository)
    {
        $article = $articleRepository->find($id);

        return $this->render('Components/customer/article/article.html.twig', [
            'article' => $article
        ]);
    }
}

app/templates/Components/admin/articles/articles.html.twig
{% extends 'Common/base.html.twig' %}

{% block stylesheets %}

    {{ parent() }}

   <link rel="stylesheet" type="text/css" href="{{ asset('CSS/admin/articles/list_articles.css') }}">

{% endblock %}

{% block content %}

    <div class="home_admin">

        <div class="header-common">
            <h1>Gestion des articles</h1>
            <a class="btn btn-primary" href="{{ path('admin_article_new') }}">Créer un articles</a>
        </div>

        <div class="tables">


            <table class="table text-center col-8">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom</th>
                        <th>Prix</th>
                        <th>Catégories</th>
                        <th>Supprimé ?</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>



                    {% for article in articles %}
                        <tr>
                            <td>{{ article.id }}</td>
                            <td>{{ article.libelle }}</td>
                            <td>{{ article.price }} €</td>
                            <td>
                                {% if article.category %}
                                    {% for category in article.category %}
                                        <a href="#">{{ category.libelle }}</a>
                                    {% endfor %}
                                {% endif %}
                            </td>
                            <td>
                                {% if article.whenDeleted is null %}
                                    <i class="fas fa-times"></i>
                                {% else %}
                                    {{ article.whenDeleted|date('d/m/Y') }}
                                {% endif %}
                            </td>
                            <td>
                                <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapse{{article.id }}" role="button" aria-expanded="false" aria-controls="collapseExample">
                                    Voir les quantités
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
{# Modifier pour afficher en les variation d'article avec le taille et la quantité #}
{#  
                <table class="table text-center col-4">
                    <thead>
                        <tr>
                            <th>Taille</th>
                            <th>Quantité</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                        {% for article in articles %}
                            <div class="collapse" id="collapse{{ article.id }}">
                                <div class="card card-body">
                                    <tbody>
                                        {% for variation_a in v_articles %}
                                            {% if variation_a.article.id == article.id %}
                                                <tr>
                                                    <td>{{ variation_a.size }}</td>
                                                    <td>{{ variation_a.quantity }}</td>
                                                    <td></td>
                                                </tr>
                                            {% endif %}
                                        {% endfor %}
                                    </tbody>
                                </div>
                            </div>
                        {% endfor %}
                </table>
#}    

        </div>

{% endblock %}

{% block javascripts %}

    {{ parent() }}

{% endblock %}

app/templates/Components/admin/articles/new_update_article.html.twig
{% extends 'Common/base.html.twig' %}

{% block content %}

    <div class="new_update_admin">

        <div class="header-new-update">
            <h1>Créer un articles</h1>
        </div>

        {{ form_start(form) }}

            <div class="content">
                {{ form_label(form.libelle) }}
                {{ form_widget(form.libelle, {'attr' : {'class' : 'form-control'}}) }}
            </div>

            <div class="content">
                {{ form_label(form.price) }}
                {{ form_widget(form.price, {'attr' : {'class' : 'form-control'}}) }}
            </div>

            <div class="content">
                {{ form_label(form.description) }}
                {{ form_widget(form.description, {'attr' : {'class' : 'form-control'}}) }}
            </div>

            <div class="content">
                {{ form_label(form.img) }}
                {{ form_widget(form.img, {'attr' : {'class' : 'form-control'}}) }}
            </div>

            <div class="content">
                {{ form_label(form.img_alt) }}
                {{ form_widget(form.img_alt, {'attr' : {'class' : 'form-control'}}) }}
            </div>

            <div class="content">
                {{ form_label(form.promo) }}
                {{ form_widget(form.promo, {'attr' : {'class' : 'form-control'}}) }}
            </div>

            <div class="content">
                {{ form_label(form.category) }}
                {{ form_widget(form.category, {'attr' : {'class' : 'form-control'}}) }}
            </div>

            {% if form.when_deleted is defined %}
                <div class="content">
                    {{ form_label(form.when_deleted) }}
                    {{ form_widget(form.when_deleted, {'attr' : {'class' : 'form-control'}}) }}
                </div>
            {% endif %}

            <button class= "btn btn-success mt-5 mb-5" type= "submit">Valider</button>

        {{ form_end(form) }}


    </div>


{% endblock %}

app/templates/Components/admin/articles/stock_article.html.twig
{% extends 'Common/base.html.twig' %}

{% block stylesheets %}

  {{ parent() }}

   <link rel="stylesheet" type="text/css" href="{{ asset('CSS/admin/articles/stock_article.css') }}">

{% endblock %}

{% block content %}

    <div class="stock_article_admin">

        <div class="header-stock-article">
            <h1>Gestion des stocks</h1>
            <button type="button" class="btn btn-danger">Retour</button>
        </div>

        <table class="table text-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nom</th>
                    <th>Taille</th>
                    <th>Prix</th>
                    <th>Supprimé ?</th>
                    <th>Quantité</th>
                    <th>Ajouter du stock</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Article 1</td>
                    <td>M</td>
                    <td>12.80€</td>
                    <td>False</td>
                    <td>35</td>
                    <td>
                        <form action ="#" method="post" enctype="multipart/form-data">
                            <div class="content">
                                <input class="form-control" type="number" id="quantity" name="qu antity" min="0" value="0">
                                <button type="submit" class="btn btn-success">Ajouter</button>
                            </div>
                        </form>
                    </td>
                </tr>

            </tbody>

        </table>

    </div>


{% endblock %}